/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgentTone = IDL.Variant({
  'professional' : IDL.Null,
  'friendly' : IDL.Null,
  'casual' : IDL.Null,
  'formal' : IDL.Null,
});
export const BusinessCategory = IDL.Variant({
  'Gym' : IDL.Null,
  'Salon' : IDL.Null,
  'Coaching' : IDL.Null,
  'RealEstate' : IDL.Null,
  'Clinic' : IDL.Null,
  'Restaurant' : IDL.Null,
});
export const AgentLanguage = IDL.Variant({
  'hindi' : IDL.Null,
  'marathi' : IDL.Null,
  'english' : IDL.Null,
});
export const AgentConfigInput = IDL.Record({
  'customInstructions' : IDL.Text,
  'tone' : AgentTone,
  'useCase' : BusinessCategory,
  'agentName' : IDL.Text,
  'language' : AgentLanguage,
});
export const AgentStatus = IDL.Variant({
  'active' : IDL.Null,
  'paused' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const AgentConfigView = IDL.Record({
  'status' : AgentStatus,
  'businessId' : IDL.Text,
  'customInstructions' : IDL.Text,
  'createdAt' : Timestamp,
  'tone' : AgentTone,
  'useCase' : BusinessCategory,
  'agentName' : IDL.Text,
  'agentId' : IDL.Text,
  'language' : AgentLanguage,
});
export const AIPersonality = IDL.Record({
  'tone' : AgentTone,
  'language' : AgentLanguage,
});
export const BusinessProfileInput = IDL.Record({
  'aiPersonality' : AIPersonality,
  'businessName' : IDL.Text,
  'whatsapp' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'category' : BusinessCategory,
  'phone' : IDL.Text,
});
export const UserId = IDL.Principal;
export const BusinessProfileView = IDL.Record({
  'businessId' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'aiPersonality' : AIPersonality,
  'businessName' : IDL.Text,
  'whatsapp' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'logoUrl' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'category' : BusinessCategory,
  'phone' : IDL.Text,
});
export const CallStatus = IDL.Variant({
  'Transferred' : IDL.Null,
  'Missed' : IDL.Null,
  'Completed' : IDL.Null,
});
export const CallLogInput = IDL.Record({
  'callerPhone' : IDL.Text,
  'callStatus' : CallStatus,
  'businessId' : IDL.Text,
  'recordingUrl' : IDL.Opt(IDL.Text),
  'agentId' : IDL.Opt(IDL.Text),
  'transcriptSnippet' : IDL.Opt(IDL.Text),
  'durationSeconds' : IDL.Nat,
  'calleePhone' : IDL.Text,
});
export const CallLogView = IDL.Record({
  'callerPhone' : IDL.Text,
  'callStatus' : CallStatus,
  'businessId' : IDL.Text,
  'recordingUrl' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'agentId' : IDL.Opt(IDL.Text),
  'transcriptSnippet' : IDL.Opt(IDL.Text),
  'durationSeconds' : IDL.Nat,
  'callId' : IDL.Text,
  'calleePhone' : IDL.Text,
});
export const LeadSource = IDL.Variant({
  'AICall' : IDL.Null,
  'Manual' : IDL.Null,
});
export const LeadPriority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const LeadRecordInput = IDL.Record({
  'customerName' : IDL.Text,
  'propertyType' : IDL.Opt(IDL.Text),
  'source' : LeadSource,
  'businessId' : IDL.Text,
  'agentId' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'siteVisitInterest' : IDL.Bool,
  'notes' : IDL.Text,
  'buyingTimeline' : IDL.Opt(IDL.Text),
  'priority' : LeadPriority,
  'phone' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const LeadStatus = IDL.Variant({
  'New' : IDL.Null,
  'Closed' : IDL.Null,
  'Qualified' : IDL.Null,
  'Scheduled' : IDL.Null,
});
export const LeadRecordView = IDL.Record({
  'customerName' : IDL.Text,
  'status' : LeadStatus,
  'propertyType' : IDL.Opt(IDL.Text),
  'source' : LeadSource,
  'businessId' : IDL.Text,
  'createdAt' : Timestamp,
  'agentId' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'leadId' : IDL.Text,
  'siteVisitInterest' : IDL.Bool,
  'notes' : IDL.Text,
  'buyingTimeline' : IDL.Opt(IDL.Text),
  'priority' : LeadPriority,
  'phone' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'enterprise' : IDL.Null,
  'free' : IDL.Null,
  'basic' : IDL.Null,
});
export const UserProfileView = IDL.Record({
  'userId' : UserId,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'email' : IDL.Text,
});
export const UserProfileData = IDL.Record({
  'subscriptionTier' : SubscriptionTier,
  'email' : IDL.Text,
});
export const AgentConfigUpdate = IDL.Record({
  'status' : AgentStatus,
  'customInstructions' : IDL.Text,
  'tone' : AgentTone,
  'useCase' : BusinessCategory,
  'agentName' : IDL.Text,
  'language' : AgentLanguage,
});
export const LeadRecordUpdate = IDL.Record({
  'customerName' : IDL.Text,
  'status' : LeadStatus,
  'propertyType' : IDL.Opt(IDL.Text),
  'agentId' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'siteVisitInterest' : IDL.Bool,
  'notes' : IDL.Text,
  'buyingTimeline' : IDL.Opt(IDL.Text),
  'priority' : LeadPriority,
  'phone' : IDL.Text,
  'budget' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAgent' : IDL.Func([IDL.Text, AgentConfigInput], [AgentConfigView], []),
  'createBusiness' : IDL.Func(
      [BusinessProfileInput],
      [BusinessProfileView],
      [],
    ),
  'createCallLog' : IDL.Func([CallLogInput], [CallLogView], []),
  'createLead' : IDL.Func([LeadRecordInput], [LeadRecordView], []),
  'deleteAgent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBusiness' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteCallLog' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteLead' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteUserProfile' : IDL.Func([], [IDL.Bool], []),
  'getAgent' : IDL.Func([IDL.Text], [IDL.Opt(AgentConfigView)], ['query']),
  'getBusiness' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BusinessProfileView)],
      ['query'],
    ),
  'getCallLog' : IDL.Func([IDL.Text], [IDL.Opt(CallLogView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLead' : IDL.Func([IDL.Text], [IDL.Opt(LeadRecordView)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfileView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAgentsByBusiness' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AgentConfigView)],
      ['query'],
    ),
  'listCallLogsByBusiness' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CallLogView)],
      ['query'],
    ),
  'listLeadsByBusiness' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeadRecordView)],
      ['query'],
    ),
  'listMyBusinesses' : IDL.Func([], [IDL.Vec(BusinessProfileView)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfileData], [UserProfileView], []),
  'updateAgent' : IDL.Func(
      [IDL.Text, AgentConfigUpdate],
      [IDL.Opt(AgentConfigView)],
      [],
    ),
  'updateBusiness' : IDL.Func(
      [IDL.Text, BusinessProfileInput],
      [IDL.Opt(BusinessProfileView)],
      [],
    ),
  'updateLead' : IDL.Func(
      [IDL.Text, LeadRecordUpdate],
      [IDL.Opt(LeadRecordView)],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [UserProfileData],
      [IDL.Opt(UserProfileView)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgentTone = IDL.Variant({
    'professional' : IDL.Null,
    'friendly' : IDL.Null,
    'casual' : IDL.Null,
    'formal' : IDL.Null,
  });
  const BusinessCategory = IDL.Variant({
    'Gym' : IDL.Null,
    'Salon' : IDL.Null,
    'Coaching' : IDL.Null,
    'RealEstate' : IDL.Null,
    'Clinic' : IDL.Null,
    'Restaurant' : IDL.Null,
  });
  const AgentLanguage = IDL.Variant({
    'hindi' : IDL.Null,
    'marathi' : IDL.Null,
    'english' : IDL.Null,
  });
  const AgentConfigInput = IDL.Record({
    'customInstructions' : IDL.Text,
    'tone' : AgentTone,
    'useCase' : BusinessCategory,
    'agentName' : IDL.Text,
    'language' : AgentLanguage,
  });
  const AgentStatus = IDL.Variant({ 'active' : IDL.Null, 'paused' : IDL.Null });
  const Timestamp = IDL.Int;
  const AgentConfigView = IDL.Record({
    'status' : AgentStatus,
    'businessId' : IDL.Text,
    'customInstructions' : IDL.Text,
    'createdAt' : Timestamp,
    'tone' : AgentTone,
    'useCase' : BusinessCategory,
    'agentName' : IDL.Text,
    'agentId' : IDL.Text,
    'language' : AgentLanguage,
  });
  const AIPersonality = IDL.Record({
    'tone' : AgentTone,
    'language' : AgentLanguage,
  });
  const BusinessProfileInput = IDL.Record({
    'aiPersonality' : AIPersonality,
    'businessName' : IDL.Text,
    'whatsapp' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'category' : BusinessCategory,
    'phone' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const BusinessProfileView = IDL.Record({
    'businessId' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'aiPersonality' : AIPersonality,
    'businessName' : IDL.Text,
    'whatsapp' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'logoUrl' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'category' : BusinessCategory,
    'phone' : IDL.Text,
  });
  const CallStatus = IDL.Variant({
    'Transferred' : IDL.Null,
    'Missed' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const CallLogInput = IDL.Record({
    'callerPhone' : IDL.Text,
    'callStatus' : CallStatus,
    'businessId' : IDL.Text,
    'recordingUrl' : IDL.Opt(IDL.Text),
    'agentId' : IDL.Opt(IDL.Text),
    'transcriptSnippet' : IDL.Opt(IDL.Text),
    'durationSeconds' : IDL.Nat,
    'calleePhone' : IDL.Text,
  });
  const CallLogView = IDL.Record({
    'callerPhone' : IDL.Text,
    'callStatus' : CallStatus,
    'businessId' : IDL.Text,
    'recordingUrl' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'agentId' : IDL.Opt(IDL.Text),
    'transcriptSnippet' : IDL.Opt(IDL.Text),
    'durationSeconds' : IDL.Nat,
    'callId' : IDL.Text,
    'calleePhone' : IDL.Text,
  });
  const LeadSource = IDL.Variant({ 'AICall' : IDL.Null, 'Manual' : IDL.Null });
  const LeadPriority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const LeadRecordInput = IDL.Record({
    'customerName' : IDL.Text,
    'propertyType' : IDL.Opt(IDL.Text),
    'source' : LeadSource,
    'businessId' : IDL.Text,
    'agentId' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'siteVisitInterest' : IDL.Bool,
    'notes' : IDL.Text,
    'buyingTimeline' : IDL.Opt(IDL.Text),
    'priority' : LeadPriority,
    'phone' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const LeadStatus = IDL.Variant({
    'New' : IDL.Null,
    'Closed' : IDL.Null,
    'Qualified' : IDL.Null,
    'Scheduled' : IDL.Null,
  });
  const LeadRecordView = IDL.Record({
    'customerName' : IDL.Text,
    'status' : LeadStatus,
    'propertyType' : IDL.Opt(IDL.Text),
    'source' : LeadSource,
    'businessId' : IDL.Text,
    'createdAt' : Timestamp,
    'agentId' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'leadId' : IDL.Text,
    'siteVisitInterest' : IDL.Bool,
    'notes' : IDL.Text,
    'buyingTimeline' : IDL.Opt(IDL.Text),
    'priority' : LeadPriority,
    'phone' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'enterprise' : IDL.Null,
    'free' : IDL.Null,
    'basic' : IDL.Null,
  });
  const UserProfileView = IDL.Record({
    'userId' : UserId,
    'createdAt' : Timestamp,
    'subscriptionTier' : SubscriptionTier,
    'email' : IDL.Text,
  });
  const UserProfileData = IDL.Record({
    'subscriptionTier' : SubscriptionTier,
    'email' : IDL.Text,
  });
  const AgentConfigUpdate = IDL.Record({
    'status' : AgentStatus,
    'customInstructions' : IDL.Text,
    'tone' : AgentTone,
    'useCase' : BusinessCategory,
    'agentName' : IDL.Text,
    'language' : AgentLanguage,
  });
  const LeadRecordUpdate = IDL.Record({
    'customerName' : IDL.Text,
    'status' : LeadStatus,
    'propertyType' : IDL.Opt(IDL.Text),
    'agentId' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'siteVisitInterest' : IDL.Bool,
    'notes' : IDL.Text,
    'buyingTimeline' : IDL.Opt(IDL.Text),
    'priority' : LeadPriority,
    'phone' : IDL.Text,
    'budget' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAgent' : IDL.Func(
        [IDL.Text, AgentConfigInput],
        [AgentConfigView],
        [],
      ),
    'createBusiness' : IDL.Func(
        [BusinessProfileInput],
        [BusinessProfileView],
        [],
      ),
    'createCallLog' : IDL.Func([CallLogInput], [CallLogView], []),
    'createLead' : IDL.Func([LeadRecordInput], [LeadRecordView], []),
    'deleteAgent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBusiness' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteCallLog' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteLead' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteUserProfile' : IDL.Func([], [IDL.Bool], []),
    'getAgent' : IDL.Func([IDL.Text], [IDL.Opt(AgentConfigView)], ['query']),
    'getBusiness' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BusinessProfileView)],
        ['query'],
      ),
    'getCallLog' : IDL.Func([IDL.Text], [IDL.Opt(CallLogView)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLead' : IDL.Func([IDL.Text], [IDL.Opt(LeadRecordView)], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAgentsByBusiness' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AgentConfigView)],
        ['query'],
      ),
    'listCallLogsByBusiness' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CallLogView)],
        ['query'],
      ),
    'listLeadsByBusiness' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeadRecordView)],
        ['query'],
      ),
    'listMyBusinesses' : IDL.Func(
        [],
        [IDL.Vec(BusinessProfileView)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfileData],
        [UserProfileView],
        [],
      ),
    'updateAgent' : IDL.Func(
        [IDL.Text, AgentConfigUpdate],
        [IDL.Opt(AgentConfigView)],
        [],
      ),
    'updateBusiness' : IDL.Func(
        [IDL.Text, BusinessProfileInput],
        [IDL.Opt(BusinessProfileView)],
        [],
      ),
    'updateLead' : IDL.Func(
        [IDL.Text, LeadRecordUpdate],
        [IDL.Opt(LeadRecordView)],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [UserProfileData],
        [IDL.Opt(UserProfileView)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };