/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIPersonality {
  'tone' : AgentTone,
  'language' : AgentLanguage,
}
export interface AgentConfigInput {
  'customInstructions' : string,
  'tone' : AgentTone,
  'useCase' : BusinessCategory,
  'agentName' : string,
  'language' : AgentLanguage,
}
export interface AgentConfigUpdate {
  'status' : AgentStatus,
  'customInstructions' : string,
  'tone' : AgentTone,
  'useCase' : BusinessCategory,
  'agentName' : string,
  'language' : AgentLanguage,
}
export interface AgentConfigView {
  'status' : AgentStatus,
  'businessId' : string,
  'customInstructions' : string,
  'createdAt' : Timestamp,
  'tone' : AgentTone,
  'useCase' : BusinessCategory,
  'agentName' : string,
  'agentId' : string,
  'language' : AgentLanguage,
}
export type AgentLanguage = { 'hindi' : null } |
  { 'marathi' : null } |
  { 'english' : null };
export type AgentStatus = { 'active' : null } |
  { 'paused' : null };
export type AgentTone = { 'professional' : null } |
  { 'friendly' : null } |
  { 'casual' : null } |
  { 'formal' : null };
export type BusinessCategory = { 'Gym' : null } |
  { 'Salon' : null } |
  { 'Coaching' : null } |
  { 'RealEstate' : null } |
  { 'Clinic' : null } |
  { 'Restaurant' : null };
export interface BusinessProfileInput {
  'aiPersonality' : AIPersonality,
  'businessName' : string,
  'whatsapp' : [] | [string],
  'email' : string,
  'logoUrl' : [] | [string],
  'address' : string,
  'category' : BusinessCategory,
  'phone' : string,
}
export interface BusinessProfileView {
  'businessId' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'aiPersonality' : AIPersonality,
  'businessName' : string,
  'whatsapp' : [] | [string],
  'email' : string,
  'logoUrl' : [] | [string],
  'address' : string,
  'category' : BusinessCategory,
  'phone' : string,
}
export interface CallLogInput {
  'callerPhone' : string,
  'callStatus' : CallStatus,
  'businessId' : string,
  'recordingUrl' : [] | [string],
  'agentId' : [] | [string],
  'transcriptSnippet' : [] | [string],
  'durationSeconds' : bigint,
  'calleePhone' : string,
}
export interface CallLogView {
  'callerPhone' : string,
  'callStatus' : CallStatus,
  'businessId' : string,
  'recordingUrl' : [] | [string],
  'createdAt' : Timestamp,
  'agentId' : [] | [string],
  'transcriptSnippet' : [] | [string],
  'durationSeconds' : bigint,
  'callId' : string,
  'calleePhone' : string,
}
export type CallStatus = { 'Transferred' : null } |
  { 'Missed' : null } |
  { 'Completed' : null };
export type LeadPriority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface LeadRecordInput {
  'customerName' : string,
  'propertyType' : [] | [string],
  'source' : LeadSource,
  'businessId' : string,
  'agentId' : [] | [string],
  'email' : [] | [string],
  'siteVisitInterest' : boolean,
  'notes' : string,
  'buyingTimeline' : [] | [string],
  'priority' : LeadPriority,
  'phone' : string,
  'budget' : [] | [string],
  'location' : [] | [string],
}
export interface LeadRecordUpdate {
  'customerName' : string,
  'status' : LeadStatus,
  'propertyType' : [] | [string],
  'agentId' : [] | [string],
  'email' : [] | [string],
  'siteVisitInterest' : boolean,
  'notes' : string,
  'buyingTimeline' : [] | [string],
  'priority' : LeadPriority,
  'phone' : string,
  'budget' : [] | [string],
  'location' : [] | [string],
}
export interface LeadRecordView {
  'customerName' : string,
  'status' : LeadStatus,
  'propertyType' : [] | [string],
  'source' : LeadSource,
  'businessId' : string,
  'createdAt' : Timestamp,
  'agentId' : [] | [string],
  'email' : [] | [string],
  'updatedAt' : Timestamp,
  'leadId' : string,
  'siteVisitInterest' : boolean,
  'notes' : string,
  'buyingTimeline' : [] | [string],
  'priority' : LeadPriority,
  'phone' : string,
  'budget' : [] | [string],
  'location' : [] | [string],
}
export type LeadSource = { 'AICall' : null } |
  { 'Manual' : null };
export type LeadStatus = { 'New' : null } |
  { 'Closed' : null } |
  { 'Qualified' : null } |
  { 'Scheduled' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'enterprise' : null } |
  { 'free' : null } |
  { 'basic' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfileData {
  'subscriptionTier' : SubscriptionTier,
  'email' : string,
}
export interface UserProfileView {
  'userId' : UserId,
  'createdAt' : Timestamp,
  'subscriptionTier' : SubscriptionTier,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAgent' : ActorMethod<[string, AgentConfigInput], AgentConfigView>,
  'createBusiness' : ActorMethod<[BusinessProfileInput], BusinessProfileView>,
  'createCallLog' : ActorMethod<[CallLogInput], CallLogView>,
  'createLead' : ActorMethod<[LeadRecordInput], LeadRecordView>,
  'deleteAgent' : ActorMethod<[string], boolean>,
  'deleteBusiness' : ActorMethod<[string], boolean>,
  'deleteCallLog' : ActorMethod<[string], boolean>,
  'deleteLead' : ActorMethod<[string], boolean>,
  'deleteUserProfile' : ActorMethod<[], boolean>,
  'getAgent' : ActorMethod<[string], [] | [AgentConfigView]>,
  'getBusiness' : ActorMethod<[string], [] | [BusinessProfileView]>,
  'getCallLog' : ActorMethod<[string], [] | [CallLogView]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLead' : ActorMethod<[string], [] | [LeadRecordView]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAgentsByBusiness' : ActorMethod<[string], Array<AgentConfigView>>,
  'listCallLogsByBusiness' : ActorMethod<[string], Array<CallLogView>>,
  'listLeadsByBusiness' : ActorMethod<[string], Array<LeadRecordView>>,
  'listMyBusinesses' : ActorMethod<[], Array<BusinessProfileView>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileData], UserProfileView>,
  'updateAgent' : ActorMethod<
    [string, AgentConfigUpdate],
    [] | [AgentConfigView]
  >,
  'updateBusiness' : ActorMethod<
    [string, BusinessProfileInput],
    [] | [BusinessProfileView]
  >,
  'updateLead' : ActorMethod<[string, LeadRecordUpdate], [] | [LeadRecordView]>,
  'updateUserProfile' : ActorMethod<[UserProfileData], [] | [UserProfileView]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];