/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface BusinessProfileInput {
    aiPersonality: AIPersonality;
    businessName: string;
    whatsapp?: string;
    email: string;
    logoUrl?: string;
    address: string;
    category: BusinessCategory;
    phone: string;
}
export interface AgentConfigInput {
    customInstructions: string;
    tone: AgentTone;
    useCase: BusinessCategory;
    agentName: string;
    language: AgentLanguage;
}
export interface CallLogView {
    callerPhone: string;
    callStatus: CallStatus;
    businessId: string;
    recordingUrl?: string;
    createdAt: Timestamp;
    agentId?: string;
    transcriptSnippet?: string;
    durationSeconds: bigint;
    callId: string;
    calleePhone: string;
}
export interface BusinessProfileView {
    businessId: string;
    userId: UserId;
    createdAt: Timestamp;
    aiPersonality: AIPersonality;
    businessName: string;
    whatsapp?: string;
    email: string;
    logoUrl?: string;
    address: string;
    category: BusinessCategory;
    phone: string;
}
export type UserId = Principal;
export interface AIPersonality {
    tone: AgentTone;
    language: AgentLanguage;
}
export interface AgentConfigUpdate {
    status: AgentStatus;
    customInstructions: string;
    tone: AgentTone;
    useCase: BusinessCategory;
    agentName: string;
    language: AgentLanguage;
}
export interface CallLogInput {
    callerPhone: string;
    callStatus: CallStatus;
    businessId: string;
    recordingUrl?: string;
    agentId?: string;
    transcriptSnippet?: string;
    durationSeconds: bigint;
    calleePhone: string;
}
export interface AgentConfigView {
    status: AgentStatus;
    businessId: string;
    customInstructions: string;
    createdAt: Timestamp;
    tone: AgentTone;
    useCase: BusinessCategory;
    agentName: string;
    agentId: string;
    language: AgentLanguage;
}
export interface UserProfileView {
    userId: UserId;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    email: string;
}
export interface UserProfileData {
    subscriptionTier: SubscriptionTier;
    email: string;
}
export interface LeadRecordInput {
    customerName: string;
    propertyType?: string;
    source: LeadSource;
    businessId: string;
    agentId?: string;
    email?: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline?: string;
    priority: LeadPriority;
    phone: string;
    budget?: string;
    location?: string;
}
export interface LeadRecordView {
    customerName: string;
    status: LeadStatus;
    propertyType?: string;
    source: LeadSource;
    businessId: string;
    createdAt: Timestamp;
    agentId?: string;
    email?: string;
    updatedAt: Timestamp;
    leadId: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline?: string;
    priority: LeadPriority;
    phone: string;
    budget?: string;
    location?: string;
}
export interface LeadRecordUpdate {
    customerName: string;
    status: LeadStatus;
    propertyType?: string;
    agentId?: string;
    email?: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline?: string;
    priority: LeadPriority;
    phone: string;
    budget?: string;
    location?: string;
}
export enum AgentLanguage {
    hindi = "hindi",
    marathi = "marathi",
    english = "english"
}
export enum AgentStatus {
    active = "active",
    paused = "paused"
}
export enum AgentTone {
    professional = "professional",
    friendly = "friendly",
    casual = "casual",
    formal = "formal"
}
export enum BusinessCategory {
    Gym = "Gym",
    Salon = "Salon",
    Coaching = "Coaching",
    RealEstate = "RealEstate",
    Clinic = "Clinic",
    Restaurant = "Restaurant"
}
export enum CallStatus {
    Transferred = "Transferred",
    Missed = "Missed",
    Completed = "Completed"
}
export enum LeadPriority {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum LeadSource {
    AICall = "AICall",
    Manual = "Manual"
}
export enum LeadStatus {
    New = "New",
    Closed = "Closed",
    Qualified = "Qualified",
    Scheduled = "Scheduled"
}
export enum SubscriptionTier {
    pro = "pro",
    enterprise = "enterprise",
    free = "free",
    basic = "basic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAgent(businessId: string, input: AgentConfigInput): Promise<AgentConfigView>;
    createBusiness(input: BusinessProfileInput): Promise<BusinessProfileView>;
    createCallLog(input: CallLogInput): Promise<CallLogView>;
    createLead(input: LeadRecordInput): Promise<LeadRecordView>;
    deleteAgent(agentId: string): Promise<boolean>;
    deleteBusiness(businessId: string): Promise<boolean>;
    deleteCallLog(callId: string): Promise<boolean>;
    deleteLead(leadId: string): Promise<boolean>;
    deleteUserProfile(): Promise<boolean>;
    getAgent(agentId: string): Promise<AgentConfigView | null>;
    getBusiness(businessId: string): Promise<BusinessProfileView | null>;
    getCallLog(callId: string): Promise<CallLogView | null>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLead(leadId: string): Promise<LeadRecordView | null>;
    getUserProfile(userId: UserId): Promise<UserProfileView | null>;
    isCallerAdmin(): Promise<boolean>;
    listAgentsByBusiness(businessId: string): Promise<Array<AgentConfigView>>;
    listCallLogsByBusiness(businessId: string): Promise<Array<CallLogView>>;
    listLeadsByBusiness(businessId: string): Promise<Array<LeadRecordView>>;
    listMyBusinesses(): Promise<Array<BusinessProfileView>>;
    saveCallerUserProfile(data: UserProfileData): Promise<UserProfileView>;
    updateAgent(agentId: string, input: AgentConfigUpdate): Promise<AgentConfigView | null>;
    updateBusiness(businessId: string, input: BusinessProfileInput): Promise<BusinessProfileView | null>;
    updateLead(leadId: string, input: LeadRecordUpdate): Promise<LeadRecordView | null>;
    updateUserProfile(data: UserProfileData): Promise<UserProfileView | null>;
}
import type { AIPersonality as _AIPersonality, AgentConfigInput as _AgentConfigInput, AgentConfigUpdate as _AgentConfigUpdate, AgentConfigView as _AgentConfigView, AgentLanguage as _AgentLanguage, AgentStatus as _AgentStatus, AgentTone as _AgentTone, BusinessCategory as _BusinessCategory, BusinessProfileInput as _BusinessProfileInput, BusinessProfileView as _BusinessProfileView, CallLogInput as _CallLogInput, CallLogView as _CallLogView, CallStatus as _CallStatus, LeadPriority as _LeadPriority, LeadRecordInput as _LeadRecordInput, LeadRecordUpdate as _LeadRecordUpdate, LeadRecordView as _LeadRecordView, LeadSource as _LeadSource, LeadStatus as _LeadStatus, SubscriptionTier as _SubscriptionTier, Timestamp as _Timestamp, UserId as _UserId, UserProfileData as _UserProfileData, UserProfileView as _UserProfileView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAgent(arg0: string, arg1: AgentConfigInput): Promise<AgentConfigView> {
        if (this.processError) {
            try {
                const result = await this.actor.createAgent(arg0, to_candid_AgentConfigInput_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AgentConfigView_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAgent(arg0, to_candid_AgentConfigInput_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AgentConfigView_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBusiness(arg0: BusinessProfileInput): Promise<BusinessProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusiness(to_candid_BusinessProfileInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BusinessProfileView_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusiness(to_candid_BusinessProfileInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BusinessProfileView_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCallLog(arg0: CallLogInput): Promise<CallLogView> {
        if (this.processError) {
            try {
                const result = await this.actor.createCallLog(to_candid_CallLogInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CallLogView_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCallLog(to_candid_CallLogInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CallLogView_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLead(arg0: LeadRecordInput): Promise<LeadRecordView> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(to_candid_LeadRecordInput_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_LeadRecordView_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(to_candid_LeadRecordInput_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_LeadRecordView_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAgent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgent(arg0);
            return result;
        }
    }
    async deleteBusiness(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusiness(arg0);
            return result;
        }
    }
    async deleteCallLog(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallLog(arg0);
            return result;
        }
    }
    async deleteLead(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteUserProfile(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserProfile();
            return result;
        }
    }
    async getAgent(arg0: string): Promise<AgentConfigView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBusiness(arg0: string): Promise<BusinessProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusiness(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusiness(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallLog(arg0: string): Promise<CallLogView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallLog(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallLog(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: string): Promise<LeadRecordView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAgentsByBusiness(arg0: string): Promise<Array<AgentConfigView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAgentsByBusiness(arg0);
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAgentsByBusiness(arg0);
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCallLogsByBusiness(arg0: string): Promise<Array<CallLogView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCallLogsByBusiness(arg0);
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCallLogsByBusiness(arg0);
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLeadsByBusiness(arg0: string): Promise<Array<LeadRecordView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLeadsByBusiness(arg0);
                return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLeadsByBusiness(arg0);
            return from_candid_vec_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyBusinesses(): Promise<Array<BusinessProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBusinesses();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBusinesses();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfileData): Promise<UserProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileData_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfileView_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileData_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfileView_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAgent(arg0: string, arg1: AgentConfigUpdate): Promise<AgentConfigView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgent(arg0, to_candid_AgentConfigUpdate_n71(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgent(arg0, to_candid_AgentConfigUpdate_n71(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBusiness(arg0: string, arg1: BusinessProfileInput): Promise<BusinessProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusiness(arg0, to_candid_BusinessProfileInput_n21(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusiness(arg0, to_candid_BusinessProfileInput_n21(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLead(arg0: string, arg1: LeadRecordUpdate): Promise<LeadRecordView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_LeadRecordUpdate_n75(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_LeadRecordUpdate_n75(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: UserProfileData): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_UserProfileData_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_UserProfileData_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AIPersonality_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIPersonality): AIPersonality {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_AgentConfigView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentConfigView): AgentConfigView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_AgentLanguage_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentLanguage): AgentLanguage {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_AgentStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_AgentTone_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentTone): AgentTone {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessCategory): BusinessCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessProfileView_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessProfileView): BusinessProfileView {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CallLogView_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallLogView): CallLogView {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_LeadPriority_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadPriority): LeadPriority {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_LeadRecordView_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadRecordView): LeadRecordView {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_LeadSource_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadSource): LeadSource {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileView_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AgentConfigView]): AgentConfigView | null {
    return value.length === 0 ? null : from_candid_AgentConfigView_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BusinessProfileView]): BusinessProfileView | null {
    return value.length === 0 ? null : from_candid_BusinessProfileView_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallLogView]): CallLogView | null {
    return value.length === 0 ? null : from_candid_CallLogView_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : from_candid_UserProfileView_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeadRecordView]): LeadRecordView | null {
    return value.length === 0 ? null : from_candid_LeadRecordView_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AgentStatus;
    businessId: string;
    customInstructions: string;
    createdAt: _Timestamp;
    tone: _AgentTone;
    useCase: _BusinessCategory;
    agentName: string;
    agentId: string;
    language: _AgentLanguage;
}): {
    status: AgentStatus;
    businessId: string;
    customInstructions: string;
    createdAt: Timestamp;
    tone: AgentTone;
    useCase: BusinessCategory;
    agentName: string;
    agentId: string;
    language: AgentLanguage;
} {
    return {
        status: from_candid_AgentStatus_n13(_uploadFile, _downloadFile, value.status),
        businessId: value.businessId,
        customInstructions: value.customInstructions,
        createdAt: value.createdAt,
        tone: from_candid_AgentTone_n15(_uploadFile, _downloadFile, value.tone),
        useCase: from_candid_BusinessCategory_n17(_uploadFile, _downloadFile, value.useCase),
        agentName: value.agentName,
        agentId: value.agentId,
        language: from_candid_AgentLanguage_n19(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    businessId: string;
    userId: _UserId;
    createdAt: _Timestamp;
    aiPersonality: _AIPersonality;
    businessName: string;
    whatsapp: [] | [string];
    email: string;
    logoUrl: [] | [string];
    address: string;
    category: _BusinessCategory;
    phone: string;
}): {
    businessId: string;
    userId: UserId;
    createdAt: Timestamp;
    aiPersonality: AIPersonality;
    businessName: string;
    whatsapp?: string;
    email: string;
    logoUrl?: string;
    address: string;
    category: BusinessCategory;
    phone: string;
} {
    return {
        businessId: value.businessId,
        userId: value.userId,
        createdAt: value.createdAt,
        aiPersonality: from_candid_AIPersonality_n27(_uploadFile, _downloadFile, value.aiPersonality),
        businessName: value.businessName,
        whatsapp: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.whatsapp)),
        email: value.email,
        logoUrl: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.logoUrl)),
        address: value.address,
        category: from_candid_BusinessCategory_n17(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tone: _AgentTone;
    language: _AgentLanguage;
}): {
    tone: AgentTone;
    language: AgentLanguage;
} {
    return {
        tone: from_candid_AgentTone_n15(_uploadFile, _downloadFile, value.tone),
        language: from_candid_AgentLanguage_n19(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    callerPhone: string;
    callStatus: _CallStatus;
    businessId: string;
    recordingUrl: [] | [string];
    createdAt: _Timestamp;
    agentId: [] | [string];
    transcriptSnippet: [] | [string];
    durationSeconds: bigint;
    callId: string;
    calleePhone: string;
}): {
    callerPhone: string;
    callStatus: CallStatus;
    businessId: string;
    recordingUrl?: string;
    createdAt: Timestamp;
    agentId?: string;
    transcriptSnippet?: string;
    durationSeconds: bigint;
    callId: string;
    calleePhone: string;
} {
    return {
        callerPhone: value.callerPhone,
        callStatus: from_candid_CallStatus_n36(_uploadFile, _downloadFile, value.callStatus),
        businessId: value.businessId,
        recordingUrl: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.recordingUrl)),
        createdAt: value.createdAt,
        agentId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.agentId)),
        transcriptSnippet: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.transcriptSnippet)),
        durationSeconds: value.durationSeconds,
        callId: value.callId,
        calleePhone: value.calleePhone
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _LeadStatus;
    propertyType: [] | [string];
    source: _LeadSource;
    businessId: string;
    createdAt: _Timestamp;
    agentId: [] | [string];
    email: [] | [string];
    updatedAt: _Timestamp;
    leadId: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline: [] | [string];
    priority: _LeadPriority;
    phone: string;
    budget: [] | [string];
    location: [] | [string];
}): {
    customerName: string;
    status: LeadStatus;
    propertyType?: string;
    source: LeadSource;
    businessId: string;
    createdAt: Timestamp;
    agentId?: string;
    email?: string;
    updatedAt: Timestamp;
    leadId: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline?: string;
    priority: LeadPriority;
    phone: string;
    budget?: string;
    location?: string;
} {
    return {
        customerName: value.customerName,
        status: from_candid_LeadStatus_n46(_uploadFile, _downloadFile, value.status),
        propertyType: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.propertyType)),
        source: from_candid_LeadSource_n48(_uploadFile, _downloadFile, value.source),
        businessId: value.businessId,
        createdAt: value.createdAt,
        agentId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.agentId)),
        email: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.email)),
        updatedAt: value.updatedAt,
        leadId: value.leadId,
        siteVisitInterest: value.siteVisitInterest,
        notes: value.notes,
        buyingTimeline: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.buyingTimeline)),
        priority: from_candid_LeadPriority_n50(_uploadFile, _downloadFile, value.priority),
        phone: value.phone,
        budget: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.budget)),
        location: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    createdAt: _Timestamp;
    subscriptionTier: _SubscriptionTier;
    email: string;
}): {
    userId: UserId;
    createdAt: Timestamp;
    subscriptionTier: SubscriptionTier;
    email: string;
} {
    return {
        userId: value.userId,
        createdAt: value.createdAt,
        subscriptionTier: from_candid_SubscriptionTier_n58(_uploadFile, _downloadFile, value.subscriptionTier),
        email: value.email
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    paused: null;
}): AgentStatus {
    return "active" in value ? AgentStatus.active : "paused" in value ? AgentStatus.paused : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professional: null;
} | {
    friendly: null;
} | {
    casual: null;
} | {
    formal: null;
}): AgentTone {
    return "professional" in value ? AgentTone.professional : "friendly" in value ? AgentTone.friendly : "casual" in value ? AgentTone.casual : "formal" in value ? AgentTone.formal : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Gym: null;
} | {
    Salon: null;
} | {
    Coaching: null;
} | {
    RealEstate: null;
} | {
    Clinic: null;
} | {
    Restaurant: null;
}): BusinessCategory {
    return "Gym" in value ? BusinessCategory.Gym : "Salon" in value ? BusinessCategory.Salon : "Coaching" in value ? BusinessCategory.Coaching : "RealEstate" in value ? BusinessCategory.RealEstate : "Clinic" in value ? BusinessCategory.Clinic : "Restaurant" in value ? BusinessCategory.Restaurant : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    marathi: null;
} | {
    english: null;
}): AgentLanguage {
    return "hindi" in value ? AgentLanguage.hindi : "marathi" in value ? AgentLanguage.marathi : "english" in value ? AgentLanguage.english : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Transferred: null;
} | {
    Missed: null;
} | {
    Completed: null;
}): CallStatus {
    return "Transferred" in value ? CallStatus.Transferred : "Missed" in value ? CallStatus.Missed : "Completed" in value ? CallStatus.Completed : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Closed: null;
} | {
    Qualified: null;
} | {
    Scheduled: null;
}): LeadStatus {
    return "New" in value ? LeadStatus.New : "Closed" in value ? LeadStatus.Closed : "Qualified" in value ? LeadStatus.Qualified : "Scheduled" in value ? LeadStatus.Scheduled : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AICall: null;
} | {
    Manual: null;
}): LeadSource {
    return "AICall" in value ? LeadSource.AICall : "Manual" in value ? LeadSource.Manual : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): LeadPriority {
    return "Low" in value ? LeadPriority.Low : "High" in value ? LeadPriority.High : "Medium" in value ? LeadPriority.Medium : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    enterprise: null;
} | {
    free: null;
} | {
    basic: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "enterprise" in value ? SubscriptionTier.enterprise : "free" in value ? SubscriptionTier.free : "basic" in value ? SubscriptionTier.basic : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgentConfigView>): Array<AgentConfigView> {
    return value.map((x)=>from_candid_AgentConfigView_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallLogView>): Array<CallLogView> {
    return value.map((x)=>from_candid_CallLogView_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeadRecordView>): Array<LeadRecordView> {
    return value.map((x)=>from_candid_LeadRecordView_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BusinessProfileView>): Array<BusinessProfileView> {
    return value.map((x)=>from_candid_BusinessProfileView_n25(_uploadFile, _downloadFile, x));
}
function to_candid_AIPersonality_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AIPersonality): _AIPersonality {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_AgentConfigInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentConfigInput): _AgentConfigInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AgentConfigUpdate_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentConfigUpdate): _AgentConfigUpdate {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_AgentLanguage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentLanguage): _AgentLanguage {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_AgentStatus_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): _AgentStatus {
    return to_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function to_candid_AgentTone_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentTone): _AgentTone {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessCategory): _BusinessCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessProfileInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessProfileInput): _BusinessProfileInput {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_CallLogInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallLogInput): _CallLogInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_CallStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): _CallStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_LeadPriority_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadPriority): _LeadPriority {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_LeadRecordInput_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadRecordInput): _LeadRecordInput {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_LeadRecordUpdate_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadRecordUpdate): _LeadRecordUpdate {
    return to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_LeadSource_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): _LeadSource {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n78(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfileData_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileData): _UserProfileData {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aiPersonality: AIPersonality;
    businessName: string;
    whatsapp?: string;
    email: string;
    logoUrl?: string;
    address: string;
    category: BusinessCategory;
    phone: string;
}): {
    aiPersonality: _AIPersonality;
    businessName: string;
    whatsapp: [] | [string];
    email: string;
    logoUrl: [] | [string];
    address: string;
    category: _BusinessCategory;
    phone: string;
} {
    return {
        aiPersonality: to_candid_AIPersonality_n23(_uploadFile, _downloadFile, value.aiPersonality),
        businessName: value.businessName,
        whatsapp: value.whatsapp ? candid_some(value.whatsapp) : candid_none(),
        email: value.email,
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none(),
        address: value.address,
        category: to_candid_BusinessCategory_n7(_uploadFile, _downloadFile, value.category),
        phone: value.phone
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tone: AgentTone;
    language: AgentLanguage;
}): {
    tone: _AgentTone;
    language: _AgentLanguage;
} {
    return {
        tone: to_candid_AgentTone_n5(_uploadFile, _downloadFile, value.tone),
        language: to_candid_AgentLanguage_n9(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    callerPhone: string;
    callStatus: CallStatus;
    businessId: string;
    recordingUrl?: string;
    agentId?: string;
    transcriptSnippet?: string;
    durationSeconds: bigint;
    calleePhone: string;
}): {
    callerPhone: string;
    callStatus: _CallStatus;
    businessId: string;
    recordingUrl: [] | [string];
    agentId: [] | [string];
    transcriptSnippet: [] | [string];
    durationSeconds: bigint;
    calleePhone: string;
} {
    return {
        callerPhone: value.callerPhone,
        callStatus: to_candid_CallStatus_n32(_uploadFile, _downloadFile, value.callStatus),
        businessId: value.businessId,
        recordingUrl: value.recordingUrl ? candid_some(value.recordingUrl) : candid_none(),
        agentId: value.agentId ? candid_some(value.agentId) : candid_none(),
        transcriptSnippet: value.transcriptSnippet ? candid_some(value.transcriptSnippet) : candid_none(),
        durationSeconds: value.durationSeconds,
        calleePhone: value.calleePhone
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    propertyType?: string;
    source: LeadSource;
    businessId: string;
    agentId?: string;
    email?: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline?: string;
    priority: LeadPriority;
    phone: string;
    budget?: string;
    location?: string;
}): {
    customerName: string;
    propertyType: [] | [string];
    source: _LeadSource;
    businessId: string;
    agentId: [] | [string];
    email: [] | [string];
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline: [] | [string];
    priority: _LeadPriority;
    phone: string;
    budget: [] | [string];
    location: [] | [string];
} {
    return {
        customerName: value.customerName,
        propertyType: value.propertyType ? candid_some(value.propertyType) : candid_none(),
        source: to_candid_LeadSource_n40(_uploadFile, _downloadFile, value.source),
        businessId: value.businessId,
        agentId: value.agentId ? candid_some(value.agentId) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        siteVisitInterest: value.siteVisitInterest,
        notes: value.notes,
        buyingTimeline: value.buyingTimeline ? candid_some(value.buyingTimeline) : candid_none(),
        priority: to_candid_LeadPriority_n42(_uploadFile, _downloadFile, value.priority),
        phone: value.phone,
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customInstructions: string;
    tone: AgentTone;
    useCase: BusinessCategory;
    agentName: string;
    language: AgentLanguage;
}): {
    customInstructions: string;
    tone: _AgentTone;
    useCase: _BusinessCategory;
    agentName: string;
    language: _AgentLanguage;
} {
    return {
        customInstructions: value.customInstructions,
        tone: to_candid_AgentTone_n5(_uploadFile, _downloadFile, value.tone),
        useCase: to_candid_BusinessCategory_n7(_uploadFile, _downloadFile, value.useCase),
        agentName: value.agentName,
        language: to_candid_AgentLanguage_n9(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscriptionTier: SubscriptionTier;
    email: string;
}): {
    subscriptionTier: _SubscriptionTier;
    email: string;
} {
    return {
        subscriptionTier: to_candid_SubscriptionTier_n69(_uploadFile, _downloadFile, value.subscriptionTier),
        email: value.email
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AgentStatus;
    customInstructions: string;
    tone: AgentTone;
    useCase: BusinessCategory;
    agentName: string;
    language: AgentLanguage;
}): {
    status: _AgentStatus;
    customInstructions: string;
    tone: _AgentTone;
    useCase: _BusinessCategory;
    agentName: string;
    language: _AgentLanguage;
} {
    return {
        status: to_candid_AgentStatus_n73(_uploadFile, _downloadFile, value.status),
        customInstructions: value.customInstructions,
        tone: to_candid_AgentTone_n5(_uploadFile, _downloadFile, value.tone),
        useCase: to_candid_BusinessCategory_n7(_uploadFile, _downloadFile, value.useCase),
        agentName: value.agentName,
        language: to_candid_AgentLanguage_n9(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: LeadStatus;
    propertyType?: string;
    agentId?: string;
    email?: string;
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline?: string;
    priority: LeadPriority;
    phone: string;
    budget?: string;
    location?: string;
}): {
    customerName: string;
    status: _LeadStatus;
    propertyType: [] | [string];
    agentId: [] | [string];
    email: [] | [string];
    siteVisitInterest: boolean;
    notes: string;
    buyingTimeline: [] | [string];
    priority: _LeadPriority;
    phone: string;
    budget: [] | [string];
    location: [] | [string];
} {
    return {
        customerName: value.customerName,
        status: to_candid_LeadStatus_n77(_uploadFile, _downloadFile, value.status),
        propertyType: value.propertyType ? candid_some(value.propertyType) : candid_none(),
        agentId: value.agentId ? candid_some(value.agentId) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        siteVisitInterest: value.siteVisitInterest,
        notes: value.notes,
        buyingTimeline: value.buyingTimeline ? candid_some(value.buyingTimeline) : candid_none(),
        priority: to_candid_LeadPriority_n42(_uploadFile, _downloadFile, value.priority),
        phone: value.phone,
        budget: value.budget ? candid_some(value.budget) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentLanguage): {
    hindi: null;
} | {
    marathi: null;
} | {
    english: null;
} {
    return value == AgentLanguage.hindi ? {
        hindi: null
    } : value == AgentLanguage.marathi ? {
        marathi: null
    } : value == AgentLanguage.english ? {
        english: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallStatus): {
    Transferred: null;
} | {
    Missed: null;
} | {
    Completed: null;
} {
    return value == CallStatus.Transferred ? {
        Transferred: null
    } : value == CallStatus.Missed ? {
        Missed: null
    } : value == CallStatus.Completed ? {
        Completed: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadSource): {
    AICall: null;
} | {
    Manual: null;
} {
    return value == LeadSource.AICall ? {
        AICall: null
    } : value == LeadSource.Manual ? {
        Manual: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadPriority): {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} {
    return value == LeadPriority.Low ? {
        Low: null
    } : value == LeadPriority.High ? {
        High: null
    } : value == LeadPriority.Medium ? {
        Medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentTone): {
    professional: null;
} | {
    friendly: null;
} | {
    casual: null;
} | {
    formal: null;
} {
    return value == AgentTone.professional ? {
        professional: null
    } : value == AgentTone.friendly ? {
        friendly: null
    } : value == AgentTone.casual ? {
        casual: null
    } : value == AgentTone.formal ? {
        formal: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    enterprise: null;
} | {
    free: null;
} | {
    basic: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.enterprise ? {
        enterprise: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value == SubscriptionTier.basic ? {
        basic: null
    } : value;
}
function to_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgentStatus): {
    active: null;
} | {
    paused: null;
} {
    return value == AgentStatus.active ? {
        active: null
    } : value == AgentStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    New: null;
} | {
    Closed: null;
} | {
    Qualified: null;
} | {
    Scheduled: null;
} {
    return value == LeadStatus.New ? {
        New: null
    } : value == LeadStatus.Closed ? {
        Closed: null
    } : value == LeadStatus.Qualified ? {
        Qualified: null
    } : value == LeadStatus.Scheduled ? {
        Scheduled: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessCategory): {
    Gym: null;
} | {
    Salon: null;
} | {
    Coaching: null;
} | {
    RealEstate: null;
} | {
    Clinic: null;
} | {
    Restaurant: null;
} {
    return value == BusinessCategory.Gym ? {
        Gym: null
    } : value == BusinessCategory.Salon ? {
        Salon: null
    } : value == BusinessCategory.Coaching ? {
        Coaching: null
    } : value == BusinessCategory.RealEstate ? {
        RealEstate: null
    } : value == BusinessCategory.Clinic ? {
        Clinic: null
    } : value == BusinessCategory.Restaurant ? {
        Restaurant: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
